### ISSUE TITLE
can't upload photo on comment Facebook mobile

### ISSUE THREAD

**Issue by sadex99** [m-khvoinitsky/dark-background-light-text-extension#72] opened 2017-04-03 05:45 UTC
can't upload photo on comment Facebook mobile when this addon active, but when I turn off, its ok. please fix it, I love this addon. thanks

**Comment by m-khvoinitsky** [comment] 2017-04-25 21:05
duplicate of #57

**Closed by m-khvoinitsky** 2017-04-25 21:05 UTC
Labels: duplicate
