### ISSUE TITLE
Latest updates issues

### ISSUE THREAD

**Issue by lyndhurst** [m-khvoinitsky/dark-background-light-text-extension#115] opened 2017-11-13 23:25 UTC
I am looking for a way to get the addon back the way it used to be ... just perfect..
Since the last update I have pages that just make the browser crash, most do not display correctly, many elements are lost visually, and it did not use to be the case.. 
I'd rather a thousand times change browser than stop using your add on , is there a way or should I patiently wait for a fix? 
Thanks for letting us know, in the meantime I ll look into downgrading mozilla or something like that..
Thanks a lot also for this great tool btw..

**Comment by m-khvoinitsky** [comment] 2017-11-14 18:57
All issues you reported are known and most of them are actually Firefox bugs or bugs caused by workarounds of Firefox bugs. For reference: [bug 1412345](https://bugzilla.mozilla.org/show_bug.cgi?id=1412345), [bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022).
You can get rid of crashes by upgrading to 57. Or you can use 52.x ESR and 0.5.14 add-on version while most of the issues will be fixed.

**Closed by m-khvoinitsky** 2017-11-14 18:57 UTC
