### ISSUE TITLE
Facebook- Attach Photo or Video in Comments Section Broken

### ISSUE THREAD

**Issue by EnsignEpic** [m-khvoinitsky/dark-background-light-text-extension#160] opened 2018-02-24 01:39 UTC
Issue is as it sounds. For whatever reason, Stylesheet Processor and Simple CSS break the ability to click the button that allows you to attach images or videos to comments on a post.  What's really weird is that it has no impact on the emoji, gif, or sticker buttons; it's only the button that launches the explorer-style dialogue that causes it. The button does works in Invert, if you can manage to click it; however FB does not play nicely with Invert, causing automatic scrolls to the bottom of a page if you get too close.

**Comment by m-khvoinitsky** [comment] 2018-03-10 20:52
Duplicate of #57

**Closed** 2018-03-10 20:53 UTC
