### ISSUE TITLE
PayPal not working with latest release

### ISSUE THREAD

**Issue by beetleblaster** [m-khvoinitsky/dark-background-light-text-extension#116] opened 2017-11-14 03:35 UTC
PayPal now gives a blank screen or briefly blinks in and out. If I am quick enough, I can click the login button before it disappears, but then once I am logged in, the Dashboard page shows blank.
I have to completely disable the plugin for PayPal to work.
Even if I selectively disable the plugin for PayPal pages, the problem persists.
Also, I it may be the case that the new version is slowing things down.

**Comment by m-khvoinitsky** [comment] 2017-11-14 19:00
Duplicate of #114. Well, #114 is about Nextcloud, but the problem is the same.

**Closed by m-khvoinitsky** 2017-11-14 19:00 UTC
