### ISSUE TITLE
black page for images

### ISSUE THREAD

**Issue by Jan02** [m-khvoinitsky/dark-background-light-text-extension#18] opened 2016-05-24 15:26 UTC
activates on media display (i.e. when only an image is displayed), creates black and can't see image
version 0.5.5

**Comment by m-khvoinitsky** [comment] 2016-05-24 15:56
Do you mean black semi-transparent images?

**Comment by Jan02** [comment] 2016-05-24 17:09
no its doing that for all images, even jpgs

**Comment by m-khvoinitsky** [comment] 2016-05-24 20:42
Well, that's strange. I'm not experiencing the same issue. 
Does images became visible when you:
* disable add-on for specific website?
* uncheck "Enabled" in add-on's popup?
* disable add-on completely (in about:addons)?

**Comment by Jan02** [comment] 2016-05-31 08:13
@m-khvoinitsky yes if I disable the add-on, the image displays correctly

**Comment by m-khvoinitsky** [comment] 2016-05-31 09:34
Please, answer all questions.

Also, which other add-ons do you have installed?

**Comment by m-khvoinitsky** [comment] 2016-08-02 15:37
@Jan02, any information?

**Comment by m-khvoinitsky** [comment] 2016-08-26 15:48
User seems gone. Closing because it's not enough information to reproduce an issue.

**Closed by m-khvoinitsky** 2016-08-26 15:48 UTC
