### ISSUE TITLE
Feature request: Please let us sync our DBLT site preferences

### ISSUE THREAD

**Issue by hub2git** [m-khvoinitsky/dark-background-light-text-extension#235] opened 2020-03-02 22:59 UTC
Dear @m-khvoinitsky,
 
Thank you for a most useful extension.

Could I kindly ask you to implement [syncing ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync ) of DarkBackgroundLightText data between devices?

This way, when I sign into my Firefox account at work or at a library, I don't have to specify my DBLT preferences again (e.g., invert for gmail and google calendar; disabled for google keep

My request was inspired after the Firefox developers implemented [syncing for Multi-Account Containers](https://blog.mozilla.org/security/2020/02/06/multi-account-containers-sync/).

Thank you very much.

**Comment by m-khvoinitsky** [comment] 2020-03-20 20:08
Yes, it should be done someday.

Duplicate of #4.

**Closed by m-khvoinitsky** 2020-03-20 20:08 UTC
