### ISSUE TITLE
Update the addon to work with FF 57

### ISSUE THREAD

**Issue by dwuttke90** [m-khvoinitsky/dark-background-light-text-extension#89] opened 2017-08-23 18:12 UTC
Hey there,

first of all i have to say that this addon is by far the best night mode addon i did ever use. So i would love to still use it if the stable FF disables all legacy addons.
There are any plans about updating this addon to be compatible with the new way of addons in FF? As soon as FF stable hits version 57 this addon would be dead otherwise.

Hopefully there will be a positive answer ;)

**Comment by m-khvoinitsky** [comment] 2017-08-23 18:32
Duplicate of #71 
And yes, the work is in progress.

**Closed by m-khvoinitsky** 2017-08-23 18:32 UTC

**Comment by dwuttke90** [comment] 2017-08-23 18:37
rly fast man ;) thx alot. and sry for duplicating. didnt look careful enough...
