### ISSUE TITLE
causing crash

### ISSUE THREAD

**Issue by potato404** [m-khvoinitsky/dark-background-light-text-extension#102] opened 2017-11-09 21:29 UTC
Note by @m-khvoinitsky:
The reason for it is [Firefox bug 1412345](https://bugzilla.mozilla.org/show_bug.cgi?id=1412345)
If you on a Desktop v56, just upgrade to 57
The issue still occurs on Firefox for Android 57, currently there is no known workaround, I'm working on it.
**UPD:** should be fixed in 0.6.4.

Original comment by  @potato404:
when i visit http://liberspark.com with dark background light text enabled with default settings it crashes firefox when disabled nothing happens using firefox 56.0.2 (64-bit)

**Comment by Exagone313** [comment] 2017-11-09 23:41
I'm affected too on a self-built Firefox on Arch Linux x86-64. Firefox segfaulted when loading Slack.
I downgraded to the previous version and disabled the update until Firefox get corrected.
I don't have the time to make an issue on Bugzilla, but if you, as a webextension developer, can spot where the Firefox crash happens it would be nice.

**Comment by m-khvoinitsky** [comment] 2017-11-10 04:18
Yep, it reproduces on 56 for both mentioned websites. However, it works on 57 which will be released in 4 days so I think it doesn't makes sense to even report this bug.

**Comment by forte916** [comment] 2017-11-10 10:10
I'm faced same issue when visiting https://hackmd.io/s/S1kLEr5x

**Comment by robertgroh** [comment] 2017-11-10 10:39
The new Web-Extension also crashes my Firefox 56.0.2 on github.com.

Here is the corresponding Mozilla Crash Report: https://crash-stats.mozilla.com/report/index/f68514eb-8b94-4e93-aa1d-7ec6c0171110

**Comment by m-khvoinitsky** [comment] 2017-11-10 10:44
Thank you for the link. According to it, bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1412345

firefox56 affected, firefox57 unaffected, firefox58 fixed

If you are affected, until 57 release, you can use 0.5.14 version of the add-on (their preferences are compatible).

**Comment by negativoZero** [comment] 2017-11-10 14:43
firefox is crashing at github with the extension activated

**Comment by paddlepaw** [comment] 2017-11-10 14:54
Hi, love this extension but it is crashing firefox for any url on localhost like https://localhost and http://localhost.

**Comment by simoniz0r** [comment] 2017-11-10 14:56
>firefox is crashing at github with the extension activated

>Hi, love this extension but it is crashing firefox for any url on localhost like https://localhost and http://localhost.

>If you are affected, until 57 release, you can use 0.5.14 version of the add-on (their preferences are compatible).

Have you guys tried downgrading the extension or using FF 57+?

**Comment by paddlepaw** [comment] 2017-11-10 15:23
Downgrading worked.  Thanks for the fast response.

On Nov 10, 2017 9:56 AM, "simonizor" <notifications@github.com> wrote:

firefox is crashing at github with the extension activated

Hi, love this extension but it is crashing firefox for any url on localhost
like https://localhost and http://localhost.

If you are affected, until 57 release, you can use 0.5.14 version of the
add-on (their preferences are compatible).

Have you guys tried downgrading the extension or using FF 57+?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/102#issuecomment-343494585>,
or mute the thread

**Comment by m-khvoinitsky** [comment] 2017-11-14 21:13
Should be mostly fixed in 0.6.4. Please, report if you find a page which still crashes.

**Closed** 2018-01-21 11:53 UTC
