### ISSUE TITLE
Twitch.tv overlays are turned dark.

### ISSUE THREAD

**Issue by d3m0n0gr4ph1c** [m-khvoinitsky/dark-background-light-text-extension#92] opened 2017-09-08 09:25 UTC
The overlays, at least the one I checked, are from the URL ext-twitch.tv. Recommend blacklisting that URL as I had to find it in the page code, visit the URL and change it from there. Rather messy and difficult for anyone who doesn't know where to find it.

**Comment by m-khvoinitsky** [comment] 2017-10-05 09:14
Sorry for the delay, currently all my effort made on WebExtensions port. Is the problem still persists? I've tested some random streams and it works for me.

**Comment by m-khvoinitsky** [comment] 2017-10-12 09:40
I've reproduced it in #95. It seems that it's another case of #51 (iframe overlay). I guess we should not overwrite background color of <html> for iframes at all.

**Comment by Gonnno** [comment] 2017-10-12 19:58
Hello,
It seems that the black sreen intervenes only on the chains using the new system of extension of Twitch.
When I disable Dark Background and Light Text the black mask disappears.

**Comment by m-khvoinitsky** [comment] 2017-10-25 18:07
Fixed in #51. Fixed version will be released by Nov 14.

**Closed by m-khvoinitsky** 2017-10-25 18:07 UTC

**Comment by m-khvoinitsky** [comment] 2017-10-27 04:08
is_top_level_frame doesn't seems to work. Reopened #51.
