### ISSUE TITLE
Get rid of eye-blinding white flashes

### ISSUE THREAD

**Issue by zenny** [m-khvoinitsky/dark-background-light-text-extension#130] opened 2017-11-29 18:25 UTC
Hi,

The recent updates of this addon generates eye-blinding flashes before the dark style is applied to both in the Firefox Quantum and older versions of Firefox.  Please make the page load without those white flashes as this addon used to work before.

Cheers,

**Comment by SirNeon** [comment] 2017-11-30 12:53
Can confirm. I've also been experiencing this problem. I had to use Stylus to style a select elements (mostly html and body) on sites I regularly visit to get rid of white flashes.

**Comment by slk500** [comment] 2017-11-30 15:21
It's real pain. Also waiting for the fix.

**Comment by m-khvoinitsky** [comment] 2017-11-30 16:39
See https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/71#issuecomment-340042356 for details.

**Comment by lonewulfeu** [comment] 2017-12-01 12:12
@m-khvoinitsky Could this fix the issue? 
https://github.com/overdodactyl/userContent-tweaks

**Comment by m-khvoinitsky** [comment] 2017-12-03 15:56
> @m-khvoinitsky Could this fix the issue?
https://github.com/overdodactyl/userContent-tweaks

Partially yes, but I can't edit this file from the extension.

**Comment by m-khvoinitsky** [comment] 2017-12-03 15:57
This issue is complex and caused by several unrelated issues.
If you don't mind, I'll close this issue and create new meta-bug which will link all related bugs.

**Comment by m-khvoinitsky** [comment] 2017-12-03 16:20
#131

**Closed by m-khvoinitsky** 2017-12-03 16:20 UTC
