### ISSUE TITLE
SERIOUS Twitch issue

### ISSUE THREAD

**Issue by asrek101** [m-khvoinitsky/dark-background-light-text-extension#95] opened 2017-09-28 05:15 UTC
some stream on twitch wont load ( video is greyed... i can hear the sound just fine but no image )
it work if i completely kill the addon ( disabling on current page dosent work ) , the stream cut again if i enable the addon . using firefox

i don't know if everyone experience the same issue but here a stream example 
https://go.twitch.tv/gassymexican

**Comment by m-khvoinitsky** [comment] 2017-10-05 09:12
Can you provide more details? Whether it happens on all streams or only on some? It works for me now on the stream you mentioned and on some random ones. Which method do you use?

**Comment by asrek101** [comment] 2017-10-10 21:34
it seem to happen only on stream who use new ( addon ) extension feature... 
for example top destiny 2 streamer use the destiny 2 armory overlay none of them show image (if dark background is not disabled ) can still ear the sound

https://go.twitch.tv/directory/game/Destiny%202

https://go.twitch.tv/professorbroman

**Comment by m-khvoinitsky** [comment] 2017-10-12 09:35
It seems that it's another case of #51 (iframe overlay). I guess we should not overwrite background color of `<html>` for iframes at all.

**Comment by m-khvoinitsky** [comment] 2017-10-12 09:39
As was noted in #92, you should be able to open https://ext-twitch.tv/ in a new tab and disable add-on via pop-up for this domain. It should workaround the issue.
Closing this issue as a duplicate of #92

**Closed by m-khvoinitsky** 2017-10-12 09:39 UTC
