### ISSUE TITLE
flashlight when loading pages

### ISSUE THREAD

**Issue by KBeM** [m-khvoinitsky/dark-background-light-text-extension#224] opened 2019-11-07 00:38 UTC
Hi, i love this addon, best of its category that i could find. But 1 thing is very annoying. Whenever i load a new page or reload current one, Firefox briefly brings up a white screen. Which feels like camera flashlights. 
This most likely happens because the effects of this addon are applied later on, is it? 
Therefore i would like to know if there is a way to hack Firefox in using black default background while this addon keeps working? 

Settings-General-Colors-Background sadly does not help or fix this.

**Comment by m-khvoinitsky** [comment] 2019-11-08 16:16
Duplicate of #131.
Some information: the probability of this problem will be significantly reduced in a nearest update which will be released approximately in a week.

**Closed by m-khvoinitsky** 2019-11-08 16:16 UTC
