### ISSUE TITLE
Firefox crash on github when this plugin is enabled

### ISSUE THREAD

**Issue by Martin1887** [m-khvoinitsky/dark-background-light-text-extension#117] opened 2017-11-14 08:18 UTC
Hello.

I have noticed that Firefox tab crash on GitHub pages when the plugin is enabled. I hope that this issue help you to find a bug!

Thanks and regards.

**Comment by m-khvoinitsky** [comment] 2017-11-14 18:31
Duplicate of #102

**Closed by m-khvoinitsky** 2017-11-14 18:31 UTC
