### ISSUE TITLE
WebExtensions port please!

### ISSUE THREAD

**Issue by wolftune** [m-khvoinitsky/dark-background-light-text-extension#71] opened 2017-03-26 21:33 UTC
I love this and want it to keep working long-term!

**Comment by thataboy** [comment] 2017-04-18 18:06
I hope the API is there to keep this extension going.

It has just stopped working on Nightly. Sign of things to come.

**Comment by m-khvoinitsky** [comment] 2017-04-25 21:18
Certainly it will be.

> I hope the API is there to keep this extension going.

Actually, not completely. It's possible to implement almost everything except for some minor things (like processing of other add-on's pop-ups and some firefox internal pages, [avoiding white flicker on new tab opening](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/bc7bebf84f1aac3ebc6e429e79a4deb33f53beb1/data/methods/global.css#L3), [ensuring proper configuration](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/bc7bebf84f1aac3ebc6e429e79a4deb33f53beb1/lib/index.js#L408) and so on) but this is for desktop. On the other hand in case of Firefox for Android it's even worse. There is no way to implement any add-on UI at all (I need only one button and\or menu item). Likely, it seems that the support of old-school add-ons will not be dropped in Firefox for Android after v57.

Compatibility with Nightly was fixed in #74 - will be released soon.

**Comment by m-khvoinitsky** [comment] 2017-08-23 13:14
https://bugzilla.mozilla.org/show_bug.cgi?id=1393022

**Comment by glop102** [comment] 2017-09-01 22:22
using either 0.5.10 or 0.5.11 does not seem to work with 57 nightly even though it claims to work in release 0.5.10

i enabled legacy add-ons and no-script seems to work which is legacy, but there is no icon on the bar and no visible effects from your add-on

Did it break with the very latest release of nightly?
Did i do something wrong for installing it? (zip the files and disable code signing)

**Comment by m-khvoinitsky** [comment] 2017-09-02 09:19
Yes, currently there is no version compatible with Firefox 57+. Enabling legacy add-on won't help because it seems that code needed for my add-on has been removed from Firefox.

**Comment by kenstuddy** [comment] 2017-09-10 23:25
Wait, does that mean that this addon won't be able to work in Firefox 57+ unless the missing code is added back, or are things still going as planned and this addon should work fine in Firefox 57+ by the time Firefox 57+ is released?

**Comment by glop102** [comment] 2017-09-11 07:00
> missing code

yes, the code is missing. After looking up what is going on more, it seems that firefox is removing ALL support for the older plugin system. 57 is halfway there of not having the code in place to even run the old plugins, and as such the code for this plugin has already been purged or broke or something

Theoretically webextensions (the new plugin system) will still allow this plugin to work, hence this issue thread of asking it to be ported over. Firefox is still getting the full new API put in, and the creator has said he is looking into it i think, so it is mostly a waiting game.

(maybe i should look into the new system and see if i can help?)

**Comment by kenstuddy** [comment] 2017-09-11 11:26
I am still hoping for a comment from the maintainer about my question as I believe he would know best if his plugin will be "fixable" or if it's a lost cause at this point and there's nothing he can do.

**Comment by m-khvoinitsky** [comment] 2017-09-11 12:51
> Does that mean that this addon won't be able to work in Firefox 57+ unless the missing code is added back, or are things still going as planned and this addon should work fine in Firefox 57+ by the time Firefox 57+ is released?

@kenstuddy, The code will not be added back. The add-on should be significantly rewritten to be able to work on 57+. Currently, I'm working on it. Almost everything already works (except for things like stated in https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/71#issuecomment-297167926). However, there is one major issue with new API which prevents me from porting it: https://bugzilla.mozilla.org/show_bug.cgi?id=1393022. While I'm working on workaround (just in case), I hope that this will be fixed until 57 release. Otherwise, the workaround would be very slow and buggy.

@glop102, that's correct.
> (maybe i should look into the new system and see if i can help?)

Currently, my work-in-progress code is not publicly available yet (because it's a bit messy) and the most part of new API support is already done so there is not so much you can do.

**Comment by emacsomancer** [comment] 2017-09-16 15:56
> On the other hand in case of Firefox for Android it's even worse. There is no way to implement any add-on UI at all (I need only one button and\or menu item). Likely, it seems that the support of old-school add-ons will not be dropped in Firefox for Android after v57. UPD: No, it will be dropped too.

So is making this work for FF Android a lost cause?

**Comment by m-khvoinitsky** [comment] 2017-09-17 19:45
> So is making this work for FF Android a lost cause?

No. Since the time this comment has been written the situation has changed in a good way. I haven't tested WebExtensions in Firefox for Android yet but, according to the documentation, mobile version of the add-on should not suffer from porting to WebExtensions at all.

**Comment by SkyWheel** [comment] 2017-09-20 00:45
Bam! and Firefox Developer Edition has just migrated to WebExtensions... This has killed majority of my favorite add-ons. Migrating to Cyberfox now.

**Comment by kenstuddy** [comment] 2017-10-17 21:25
I just thought I'd pop my head in and see how things are going in terms of the web extensions port? This is now my only addon that doesn't yet support Firefox 57 and the new API yet so I am hoping that things are still progressing well and hoping that this will be ready around the release of Firefox 57.

**Comment by kenstuddy** [comment] 2017-10-17 21:26
I just thought I'd pop my head in and see how things are going in terms of the web extensions port? This is now my only addon that doesn't yet support Firefox 57 and the new API yet so I am hoping that things are still progressing well and hoping that this will be ready around the release of Firefox 57.

**Comment by m-khvoinitsky** [comment] 2017-10-18 09:43
Currently I'm using 57+ compatible version personally every day. There are still a lot of bugs so it even makes no sense to show it to the public to collect feedback, the most severe is almost completely not working add-on on some sites due to [bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022)/#96. From the next week I'm going on vacation on my main job to be able to spend much more time on porting.

**Comment by SkyWheel** [comment] 2017-10-18 21:10
Privet Mikhail,
Is there any chance to test new release of the add-on on some developer channel?
As soon as I'm using Firefox Developer Edition I could test it as well.

**Comment by m-khvoinitsky** [comment] 2017-10-19 14:55
Hi. You can build it youself (no fancy one-command script or Makefile though):
```bash
git clone https://github.com/m-khvoinitsky/dark-background-light-text-extension.git
cd dark-background-light-text-extension/
git checkout webextensions
git submodule init 
git submodule update
(cd ./lib/webextension-polyfill/; npm install; npm run build)
# Finally
web-ext run --firefox /usr/bin/firefox-developer
# OR
web-ext build
```
Obviously, you need to have node.js, npm and web-ext (can be installed via npm) installed.
You can even try it in Chrome.

**Comment by simoniz0r** [comment] 2017-10-25 23:35
I would very much appreciate it if you could upload beta releases to [the beta versions page on Mozilla's addons site](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/beta) so we could check out the progress and even help bug test more easily.  :D

**Comment by m-khvoinitsky** [comment] 2017-10-26 19:57
[Done.](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/beta)
Most of the features working, not yet compatible with Fennec though.

**Comment by simoniz0r** [comment] 2017-10-27 01:41
Thank you so much!  Just loaded it up, and all of the sites that I visit regularly seem to be working as expected. 👍

**Comment by tigerjack** [comment] 2017-10-27 06:58
same here, it seems to work well.

**Comment by qazip** [comment] 2017-10-27 12:06
I'm also using the beta version. Thank you for providing us with that! 

There's just one thing I don't like: The white background flash whenever we refresh a page. I suppose that's something with which we've to live, atleast for the time being?

**Comment by m-khvoinitsky** [comment] 2017-10-27 18:00
https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/98#issuecomment-340038675

Well, there are several reasons for that:
* Part of the Firefox UI (which is white) is visible until [content window](https://developer.mozilla.org/en-US/docs/Web/API/Window) for tab is created. I used to fix this by [injecting custom stylesheet](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/906ae49e5d3a8b04c449599065b1a8dcc88ee308/data/methods/global.css#L2) into Firefox main window. Now it's impossible. I'm considering to suggest Firefox developers to change this color from white to the main background color of current theme, which, I suppose, is "Compact Dark" in case of most add-on users.
* [bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022)/#96 workaround: it leads to reloading certain stylesheets which leads to flash and broken layout for a short period of time. Bug reported to Firefox, they have intention to fix it.
* delay in delivering preferences to content script due to several back-and-forth requests from content script to background script and storage. This should be profiled and eliminated.

**Comment by tigerjack** [comment] 2017-10-29 05:32
@m-khvoinitsky as for the suggestion to Firefox developers, let us know if we can help to plead your request in some way.

**Comment by m-khvoinitsky** [comment] 2017-11-05 20:40
[New beta (0.5.99b2)](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/beta?page=1#version-0.5.99b2) has been released.

**Comment by m-khvoinitsky** [comment] 2017-11-06 17:26
[New beta (0.5.99b3)](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/beta?page=1#version-0.5.99b3) with Fennec support has been released.

**Comment by CaptaPraelium** [comment] 2017-11-08 02:27
Thanks for this, I'm trying the beta now.
I notice two issues so far:
All text on youtube.com is in italics.
New tab page has a white background.
Hope this helps :)

**Comment by glop102** [comment] 2017-11-08 03:30
The new-tab page can't be changed. I believe it is something about webextensions can't change the internal style sheets used by firefox. 5 posts above this is the list of problems they he knows about, and the first bullet point is about the white scheme on many pages.

**Comment by m-khvoinitsky** [comment] 2017-11-08 09:46
> All text on youtube.com is in italics.

Fixed in 7ade65e3bdba7a96b675cb9bd38e20936eb2390d

> New tab page has a white background.

Exactly as @glop102 said. There are a lot such internal Firefox pages. Most unexpected is addons.mozilla.org. Add-on (in it's pop-up panel) will say you that "Modification of this page is not available due to Firefox restrictions" in such cases.

**Comment by m-khvoinitsky** [comment] 2017-11-08 09:53
[New beta (0.5.99b4)](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/beta?page=1#version-0.5.99b4) has been released with aforementioned fix and some fixes for Fennec.

**Comment by CaptaPraelium** [comment] 2017-11-08 16:37
I feared the new tab page was another. I agree, addons.mozilla.org was the worst of them. 
Fix for youtube confirmed working, thank you!

**Comment by m-khvoinitsky** [comment] 2017-11-08 23:27
[New beta (0.5.99b5)](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/beta?page=1#version-0.5.99b5) has been released. It includes release notes about WebExtensions version. Please note that the logic of showing or not the release notes is this: if the previous version is 0.5.x, then show release notes. While release version will be 0.6.0, the betas are 0.5.99bx, so it will be shown every upgrade up until the release, my apologies for annoyance. However, I hope that this would be the last beta.

**Comment by m-khvoinitsky** [comment] 2017-11-09 20:19
[0.6.0](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.6.0) has been released!

**Comment by m-khvoinitsky** [comment] 2017-11-11 12:58
Information for all beta users: please, switch manually to release version. If I got it correctly, it won't be done automatically. And due to the fact that I don't have stable release cycle, I can't guarantee that there always be a beta version before the release. And, yeah, [0.6.1](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.6.1) has been released, there are no beta with same fixes.

**Comment by m-khvoinitsky** [comment] 2017-11-14 22:18
This was hard but we can consider it as done. All found bugs will be tracked in their own issues.
Congratulations to everyone on Firefox 57 release!

**Closed by m-khvoinitsky** 2017-11-14 22:18 UTC
