### ISSUE TITLE
new feature key binding

### ISSUE THREAD

**Issue by Khong-Ten** [m-khvoinitsky/dark-background-light-text-extension#101] opened 2017-11-09 17:01 UTC
Just want a keyboard toggle shortcut like Ctr+Alt+b?  Something like that.. Plz? kkk

**Comment by Khong-Ten** [comment] 2017-11-09 17:02
Something like this? https://addons.mozilla.org/en-US/firefox/addon/no-javascript-addon/

**Comment by m-khvoinitsky** [comment] 2017-11-11 21:01
Duplicate of #3. Due to the fact that workaround from #3 won't work anymore, I plan to do this in some near future.

**Closed by m-khvoinitsky** 2017-11-11 21:01 UTC
