### ISSUE TITLE
strange behaviour on some sites

### ISSUE THREAD

**Issue by Kokokokoka** [m-khvoinitsky/dark-background-light-text-extension#69] opened 2017-03-10 05:07 UTC
First of all this extension is great, I've tried colour that site (slow, but good) and nosquint (has many issues but fast and comfortable, loved the option to disable background images) before, and then I've found this extension. every site worked as intended, every
but one this site is forum.zdoom.org and it still has almost the same colors, not the expected black ones.
The simple css method seems to work on this page (it seems that this method keeps background images though), but many of the elements look broken.
Can you tell what is the difference between those modes (in terms of speed and other aspects)?
And there is a lag on gmail that makes my eyes bleed (page renders white then turns black (with stylesheet processor)). is there a workaround (this happens rarely)?

**Comment by m-khvoinitsky** [comment] 2017-04-25 21:01
I apologize for the delay.
First, indeed, the difference between modes should be documented somewhere, but it isn't, I'm sorry.
So, I'll try to explain it briefly.

Stylesheet processor does not just change all colors to the ones you've configured - it tries to preserve valuable hue where possible. For example, if there is a "warning message" on a yellow background, it keeps yellow background but makes it darker so bright text is readable. Same for text colors (see, for example, [any page with highlighted code](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/bc7bebf84f1aac3ebc6e429e79a4deb33f53beb1/lib/index.js)). When the color is assumed to be not valuable, it is just replaces with the default ones (which is configurable). The assumption whether color is valuable or not is made on the fact how color is different from any shade of gray. So, if the color is some shade of gray - it is just replaced with the default one. However, in practice, sometimes even the shades of gray matters. But, unfortunately, add-on doesn't hadle such cases (may be it will be fixed at some point). [1]

One more thing that stylesheet processor does is the way it hadles background images. The problem is that some background images are useless (they only needed for "style" like some textures or whatever) - they should be removed because add-on can't know whether they are bright or dark and whether bright text will be readable on them. On the other hand some background images are vital for page usability (like icons on buttons). Stylesheet processor uses some heuristic to guess whether a background image should be removed or not. [2]

Simle CSS is much more simple and straightforward. In case of colors it just replaces all colors with default ones (including the elements where background color must be transparent [3]). And it just keeps all background images.

So, the behavior on forum.zdoom.org is expected. It initially has some shade of brown as main background color which is considered valuable by stylesheet processor ([1]). And the majority of drawbacks with Simple CSS on that website most likely connected with [2] and [3]. That's kind of edge case which is hard to handle properly.

**Closed by m-khvoinitsky** 2017-04-25 21:01 UTC
