### ISSUE TITLE
Cannot re-disable extension on Firefox 62 (currently Developer Edition)

### ISSUE THREAD

**Issue by intgr** [m-khvoinitsky/dark-background-light-text-extension#183] opened 2018-06-26 18:03 UTC
Hi. I'm using Firefox Developer Edition 62.0b2 on Linux. Since upgrading to version 62, I can enable Dark Background Light Text with the "Enable" checkbox, but unchecking that checkbox no longer does anything.

As a workaround, it's still possible to disable it on about:addons, but then I have to refresh tabs manually for it to take effect.

PS: Thank you for this extension! It's the only extension of this kind that works well with all websites that I regularly use. Great work!

**Comment by m-khvoinitsky** [comment] 2018-06-26 18:09
Duplicate of #180

**Closed by m-khvoinitsky** 2018-06-26 18:09 UTC
