### ISSUE TITLE
dropbox.com/help/ is restricted??

### ISSUE THREAD

**Issue by cgarz** [m-khvoinitsky/dark-background-light-text-extension#154] opened 2018-02-09 23:06 UTC
Hi, I don't know why but for some reason the help part of dropbox's site is activating the restricted page behaviour of DBLT.

It might be the brightest page I've ever seen. It's awful lol. Any ideas what the issue is?

I'm on kubuntu 14.04 x64. Thanks.

Edit: I did have Dropbox installed but I have tried the page after it was stopped and now also when uninstalled. No change. Also restarted Firefox in case needed. Still the same.

Edit 2: Same behaviour on windows. Is there something going on with Dropbox and Mozilla???

**Comment by m-khvoinitsky** [comment] 2018-09-09 13:55
It is absent in extensions.webextensions.restrictedDomains and shouldn't be restricted. Looks like a bug.

**Comment by m-khvoinitsky** [comment] 2018-09-09 14:16
[Reported to Mozilla.](https://bugzilla.mozilla.org/show_bug.cgi?id=1489861)
It also affects other add-ons like S3.Translator so closing this as it's definitely a Firefox bug.

**Closed by m-khvoinitsky** 2018-09-09 14:16 UTC

**Comment by m-khvoinitsky** [comment] 2018-09-09 16:46
Some update: the issue is caused by "Content-Security-Policy: sandbox ...". If there is any security concern here, it's pointless because it's easy to remove/alter aforementioned header using webRequest.onHeadersReceived and webRequestBlocking permission. So, bugzilla bugreport is still valid.

**Comment by m-khvoinitsky** [comment] 2018-09-10 05:33
https://bugzilla.mozilla.org/show_bug.cgi?id=1411641
