### ISSUE TITLE
Addon doesn't work at first page load on mobile after v0.7.x

### ISSUE THREAD

**Issue by ynakao** [m-khvoinitsky/dark-background-light-text-extension#226] opened 2019-11-14 00:45 UTC
Thanks for the great extension.

After updated to v0.7.1 on mobile, this addon sometimes doesn't work on some pages at first load. I encounterd this issue on [Github](https://github.com), [Lobsters](https://lobste.rs) so far. In that case I have to reload the page and then dark theme is applied properly. I tried to remove the latest version and reinstall v0.6.12 from addons.mozilla.org, the addon works fine.

I'm using Fennec v68.2.0 installed from F-Droid on Lineage OS 14.1 (Android version 7.1.2). v0.7.x is working fine with Firefox v70.0.1 on my desktop.

Does this issue come from older Firefox version on Android?

**Comment by gaul** [comment] 2019-11-18 11:33
I encounter the same symptoms using the latest Fennec 68.3a1 (nightly).

**Comment by github-k8n** [comment] 2019-11-19 08:59
It seems to be an interaction between this add-on and uBlock Origin, disabling the "Anti-Facebook List" seems to make it work in Fennec v68.2.0 again

**Comment by github-k8n** [comment] 2019-11-19 09:15
So, the specific list didn't help ... the issue is kind of intermittent, but I think disabling uBlock origin DOES make it work...

**Comment by m-khvoinitsky** [comment] 2019-11-23 19:30
So, this bug consists of two parts:
1. In the main Firefox for Android window: sometimes immediately after launch script which is registered with `browser.contentScripts.register` executes _before_ content script from manifest (this is happening only immediately after launch and only in Firefox for Android). Both are not designed this way but it is relatively easy to workaround. I'm going to do this soon.
2. In the [Custom Tab](https://wiki.mozilla.org/Mobile/Firefox_for_Android/custom_Tab): again, sometimes immediately after launch script which is registered with `browser.contentScripts.register` does not executes at all, only content script from manifest does. The problem seems to be that `browser.contentScripts.register` is called _after_ page load and this page is not a real tab so injecting the script with `browser.tabs.executeScript` doesn't work.
This is a bit harder to workaround taking into account the fact, that there are no way to debug Custom Tabs — no way to connect to it from `about:debugging` and there is even no way to see `console.log` output (not in logcat or somewhere else). But I'll try to do something. As a last resort is possible to disable Custom Tabs (Settings → General → Custom Tabs).

**Comment by m-khvoinitsky** [comment] 2019-11-24 21:48
Version 0.7.2 has been released with first problem fix.

**Comment by m-khvoinitsky** [comment] 2021-01-03 22:36
Haven't experienced this problem for a while with Fenix. Closing.

**Closed by m-khvoinitsky** 2021-01-03 22:36 UTC
