### ISSUE TITLE
Embed Youtube videos show black image instead of thumbnail and can't see the mini thumbnail on a video time bar

### ISSUE THREAD

**Issue by freakvox** [m-khvoinitsky/dark-background-light-text-extension#150] opened 2018-01-22 19:08 UTC
Like title says since 1-2 days ago youtube videos only show a black image instead of showing the mini thumbnail from that specific time stamp when hovering the mouse over the video's time bar.

There's also the issue of embed youtube videos not showing the thumbnail on websites and instead only a black image.

You can see both issues here: https://imgur.com/a/jzimF

**Comment by m-khvoinitsky** [comment] 2018-01-22 19:45
Same as  #148 — it's a regression caused by fix of #108 (d88575ff2f06957d001293e9e34f039e7f4b538c)

**Comment by m-khvoinitsky** [comment] 2018-01-24 12:35
Aforementioned fix has been reverted in 0.6.8. It needs more work (#151).

**Closed by m-khvoinitsky** 2018-01-24 12:35 UTC
